version: '3.4'

#services:
#  bookstoreapi:
#    image: ${DOCKER_REGISTRY-}bookstoreapi
#    build:
#      context: .
#      dockerfile: BookStoreAPI/Dockerfile

services:
  app:
    image: bookstoreapi
    environment:
      - CONNECTION_STRING=Server=DESKTOP-MS3HGPG;Database=LightsOnHeightsDb;User Id=DESKTOP-MS3HGPG\USER;
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=your-sa-password
    

